### PR TITLE
Feature/avoid creating useless tfs

### PR DESCRIPTION
**Pull request by chisarie**
Small improvements done while trying to solve the issue on discourse (https://discourse.anymal-research.org/t/gazebo2rviz-excessive-cpu-usage/641). Still, this is not a fix to that issue.

### CODE REVIEW

**Review by remod — APPROVED** [review]

**Comment by remod** [comment]
Does this solve the 100% CPU usage issue?

**Comment by chisarie** [comment]
> Does this solve the 100% CPU usage issue?

CPU usage before change: 50% for me, 300% for yoshua;
"""""""""""""" after change:    30% for me, 50% for yoshua.
So theoretically this is not really a fix i think, because his computer still have more processes running overall, but practically the cpu usage is kind of normal now. Strange.

**Comment by YoshuaNava** [comment]
Hey Eugenio,
Thanks for this 

I think it would be useful to expose some of the parameters of these nodes (i.e. the update frequency), such that the are grabbed from the ROS param server, and can be configured on premise.

What do you think?

**Comment by chisarie** [comment]
> Hey Eugenio,
> Thanks for this
> 
> I think it would be useful to expose some of the parameters of these nodes (i.e. the update frequency), such that the are grabbed from the ROS param server, and can be configured on premise.
> 
> What do you think?

Yep, good idea. It is actually implemented the launch file of gazebo2marker, but its missing from gazebo2tf. I will add it.

**Comment by chisarie** [comment]
@remod I've done a couple of last changes. If they are fine, could you merge? I don't have the rights.

**Pull request merged**
